import { randomBytes } from "node:crypto";
import type { EmailMessage, VelveAuthConfig } from "../src/core/auth/config.js";
import type { Driver } from "../src/core/db/driver.js";
import type { IdentityMode } from "../src/core/db/migrations/identity-mode.js";
import { toWebHandler } from "../src/core/http/web-handler.js";
import { encodeBase64Url } from "../src/core/keys/base64url.js";
import { rootKeyProvider } from "../src/core/keys/index.js";
import { createVelveAuth, type VelveAuth } from "../src/index.js";
import { openMigratedSchema } from "./db-fixtures.js";
import type { TestConnection } from "./db-postgres-connection.js";

export const TEST_ORIGIN = "https://app.example.com";

/** Section 8 of the repository rules: a test key is generated by the setup and never committed. */
export function testKeyProvider(): ReturnType<typeof rootKeyProvider> {
	return rootKeyProvider({
		currentVersion: 1,
		keysByVersion: { 1: encodeBase64Url(randomBytes(32)) },
	});
}

interface LoggedLine {
	readonly level: string;
	readonly message: string;
	readonly fields: Readonly<Record<string, unknown>>;
}

export interface LogSink {
	readonly lines: readonly LoggedLine[];
	readonly write: (
		level: "info" | "warn" | "error",
		message: string,
		fields?: Readonly<Record<string, unknown>>,
	) => void;
}

export function createLogSink(): LogSink {
	const lines: LoggedLine[] = [];
	return {
		get lines() {
			return lines;
		},
		write: (level, message, fields) => {
			lines.push({ level, message, fields: fields ?? {} });
		},
	};
}

/**
 * Architecture 6.19's mail dummy: it counts, it names its recipients and kinds, and it can throw,
 * because A.7 makes a throwing `send` roll the one-time token back.
 */
export interface EmailOutbox {
	readonly send: (message: EmailMessage) => Promise<void>;
	readonly messages: readonly EmailMessage[];
	readonly count: number;
	recipients(): readonly string[];
	kinds(): readonly EmailMessage["kind"][];
	failNextSend(error: Error): void;
	clear(): void;
}

function createEmailOutbox(): EmailOutbox {
	const messages: EmailMessage[] = [];
	let failure: Error | null = null;
	return {
		send: (message) => {
			const thrown = failure;
			failure = null;
			if (thrown !== null) {
				return Promise.reject(thrown);
			}
			messages.push(message);
			return Promise.resolve();
		},
		get messages() {
			return messages;
		},
		get count() {
			return messages.length;
		},
		recipients: () => messages.map((message) => message.to),
		kinds: () => messages.map((message) => message.kind),
		failNextSend: (error) => {
			failure = error;
		},
		clear: () => {
			messages.length = 0;
		},
	};
}

/**
 * Generic over the identity mode with `"email"` as the default, so a fixture for another mode adds
 * a function beside `mountAuth` rather than editing this interface — which is the one edit here
 * that would not have been a disjoint hunk (E-776).
 */
export interface MountedAuth<M extends IdentityMode = "email"> {
	readonly auth: VelveAuth<M>;
	readonly handler: (request: Request) => Promise<Response>;
	readonly connection: TestConnection;
	readonly schema: string;
	readonly log: LogSink;
	readonly email: EmailOutbox;
}

/**
 * The overrides come last, so a test that needs providers, plugins or its own send callback
 * mounted names them and everything else stays at the default this function fixes.
 */
export function configFor(
	overrides: Partial<VelveAuthConfig<"email">> & { database: Driver },
): VelveAuthConfig<"email"> {
	return {
		identity: { mode: "email" },
		keys: testKeyProvider(),
		origins: [TEST_ORIGIN],
		email: { send: () => Promise.resolve() },
		...overrides,
	} as VelveAuthConfig<"email">;
}

/**
 * The same mount in any identity mode. The identity configuration is given rather than inferred,
 * so `M` has one inference site and E-349's trap is not reopened; `configFor`'s defaults are
 * spelled out here rather than made generic for the same reason (E-783).
 */
export async function mountAuthInMode<M extends IdentityMode>(
	prefix: string,
	identity: VelveAuthConfig<M>["identity"],
	overrides: Partial<Omit<VelveAuthConfig<M>, "database" | "schema" | "identity">> = {},
): Promise<MountedAuth<M>> {
	const { connection, schema } = await openMigratedSchema(prefix);
	const log = createLogSink();
	const email = createEmailOutbox();
	const auth = createVelveAuth<M>({
		identity,
		database: connection,
		schema,
		keys: testKeyProvider(),
		origins: [TEST_ORIGIN],
		email: { send: email.send },
		log: log.write,
		...overrides,
	} as VelveAuthConfig<M>);
	return { auth, handler: toWebHandler(auth), connection, schema, log, email };
}

export async function mountAuth(
	prefix = "auth",
	overrides: Omit<Partial<VelveAuthConfig<"email">>, "database" | "schema"> = {},
): Promise<MountedAuth> {
	const { connection, schema } = await openMigratedSchema(prefix);
	const log = createLogSink();
	const email = createEmailOutbox();
	const auth = createVelveAuth(
		configFor({
			database: connection,
			schema,
			log: log.write,
			email: { send: email.send },
			...overrides,
		}),
	);
	return { auth, handler: toWebHandler(auth), connection, schema, log, email };
}

export function requestTo(
	path: string,
	options: {
		readonly method?: string;
		readonly origin?: string | null;
		readonly cookie?: string;
		readonly body?: unknown;
	} = {},
): Request {
	const headers = new Headers();
	if (options.origin !== null) {
		headers.set("Origin", options.origin ?? TEST_ORIGIN);
	}
	if (options.cookie !== undefined) {
		headers.set("Cookie", options.cookie);
	}
	const method = options.method ?? "POST";
	if (options.body !== undefined) {
		headers.set("Content-Type", "application/json");
	}
	return new Request(`https://api.example.com${path}`, {
		method,
		headers,
		...(options.body === undefined || method === "GET"
			? {}
			: { body: JSON.stringify(options.body) }),
	});
}
